shellEmulator: true

trustPolicy: no-downgrade
packages:
  - packages/*
  - apps/*

catalog:
  '@antfu/eslint-config': ^7.2.0
  '@tailwindcss/vite': 4.1.18
  '@types/node': ^25.0.10
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  eslint: ^9.39.2
  lint-staged: ^16.2.7
  lucide-vue-next: 0.545.0
  picocolors: ^1.1.1
  simple-git-hooks: ^2.13.1
  tailwind-merge: 3.4.0
  tailwindcss: ^4.1.18
  turbo: ^2.7.6
  tw-animate-css: 1.4.0
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
